import { db } from "@/db";
import { employees, attendance, employeePerformance } from "@/db/schema";
import { gte } from "drizzle-orm";

export type AttendanceStatus = "present" | "absent" | "retard" | "conge";
export interface StaffMember { id:number; matricule:string; name:string; firstName:string; lastName:string; position:string; department:string; phone:string|null; email:string|null; photo:string|null; hiredAt:string; today:AttendanceStatus|"non-pointe"; arrivalTime:string|null; rate:number; punctuality:number; performanceScore:number; workedDays:number; hoursWorked:number; tasksCompleted:number; generatedAmount:number; counts:Record<AttendanceStatus,number>; calendar:Record<string,AttendanceStatus>; dailyPerformance:Record<string,{tasks:number;hours:number;generated:number}>; }
export interface DailyStaffRow { date:string; employeeId:number; name:string; photo:string|null; matricule:string; status:AttendanceStatus; arrivalTime:string|null; tasks:number; hours:number; generated:number; }
export interface StaffDashboardData { members:StaffMember[]; dailyRows:DailyStaffRow[]; summary:{ total:number; present:number; absent:number; retard:number; conge:number; rate:number; generated:number; tasks:number; hours:number; }; monthKey:string; monthLabel:string; daysInMonth:number; firstDay:number; todayDay:number; }
const MONTHS=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"]; const iso=(d:Date)=>d.toISOString().slice(0,10);
export async function getStaffDashboard(): Promise<StaffDashboardData> {
  const now=new Date(); now.setUTCHours(0,0,0,0); const monthStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)); const daysInMonth=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0)).getUTCDate(); const firstDay=(monthStart.getUTCDay()+6)%7;
  const [staff,records,performanceRows]=await Promise.all([db.select().from(employees),db.select().from(attendance).where(gte(attendance.date,monthStart)),db.select().from(employeePerformance).where(gte(employeePerformance.date,monthStart))]);
  const todayKey=iso(now); const byEmployee=new Map<number,typeof records>(); const perfByEmployee=new Map<number,typeof performanceRows>();
  for(const r of records){const list=byEmployee.get(r.employeeId)??[]; list.push(r); byEmployee.set(r.employeeId,list);} for(const r of performanceRows){const list=perfByEmployee.get(r.employeeId)??[]; list.push(r); perfByEmployee.set(r.employeeId,list);} 
  const members:StaffMember[]=staff.map((e)=>{const list=byEmployee.get(e.id)??[]; const performances=perfByEmployee.get(e.id)??[]; const counts={present:0,absent:0,retard:0,conge:0} as Record<AttendanceStatus,number>; const calendar:Record<string,AttendanceStatus>={}; const dailyPerformance:Record<string,{tasks:number;hours:number;generated:number}>={}; for(const r of list){const status=r.status as AttendanceStatus; if(status in counts) counts[status]++; calendar[iso(r.date)]=status;} let tasksCompleted=0,hoursWorked=0,generatedAmount=0; for(const p of performances){const tasks=p.tasksCompleted; const hours=Number(p.hoursWorked); const generated=Number(p.generatedAmount); tasksCompleted+=tasks; hoursWorked+=hours; generatedAmount+=generated; dailyPerformance[iso(p.date)]={tasks,hours,generated};} const workedDays=counts.present+counts.retard; const expected=workedDays+counts.absent; const rate=expected>0?(workedDays/expected)*100:100; const punctuality=workedDays>0?(counts.present/workedDays)*100:100; const productivity=workedDays>0?Math.min(100,(tasksCompleted/workedDays/8)*100):0; const performanceScore=Math.round(rate*0.4+punctuality*0.25+productivity*0.35); const todayRecord=list.find((r)=>iso(r.date)===todayKey); return {id:e.id,matricule:e.matricule,name:`${e.firstName} ${e.lastName}`,firstName:e.firstName,lastName:e.lastName,position:e.position,department:e.department,phone:e.phone,email:e.email,photo:e.photo,hiredAt:iso(e.hiredAt),today:(todayRecord?.status as AttendanceStatus|undefined)??"non-pointe",arrivalTime:todayRecord?.arrivalTime??null,rate,punctuality,performanceScore,workedDays,hoursWorked,tasksCompleted,generatedAmount,counts,calendar,dailyPerformance};});
  const memberById=new Map(members.map((m)=>[m.id,m])); const dailyRows:DailyStaffRow[]=records.map((r)=>{const m=memberById.get(r.employeeId); if(!m) return null; const perf=m.dailyPerformance[iso(r.date)]; return {date:iso(r.date),employeeId:r.employeeId,name:m.name,photo:m.photo,matricule:m.matricule,status:r.status as AttendanceStatus,arrivalTime:r.arrivalTime,tasks:perf?.tasks??0,hours:perf?.hours??0,generated:perf?.generated??0};}).filter((r):r is DailyStaffRow=>r!==null).sort((a,b)=>b.date.localeCompare(a.date)||a.name.localeCompare(b.name));
  const summary={total:members.length,present:0,absent:0,retard:0,conge:0,rate:0,generated:0,tasks:0,hours:0}; for(const m of members){if(m.today==="present") summary.present++; if(m.today==="absent") summary.absent++; if(m.today==="retard") summary.retard++; if(m.today==="conge") summary.conge++; summary.generated+=m.generatedAmount; summary.tasks+=m.tasksCompleted; summary.hours+=m.hoursWorked;} summary.rate=members.length?members.reduce((s,m)=>s+m.rate,0)/members.length:0;
  return {members,dailyRows,summary,monthKey:`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,"0")}`,monthLabel:`${MONTHS[now.getUTCMonth()]} ${now.getUTCFullYear()}`,daysInMonth,firstDay,todayDay:now.getUTCDate()};
}
